
name: first_priority_app
description: "The official First Priority of South Florida App"
publish_to: 'none'
version: 1.0.8+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  month_picker_dialog: ^0.3.3
  dio_cookie_manager: ^2.0.0
  cached_network_image: ^2.5.0
  cookie_jar: ^3.0.1
  url_launcher: ^6.0.5
  get: ^4.1.4
  get_storage: ^1.1.6
  flutter_svg: ^0.22.0
  dio: ^4.0.0
  path_provider: ^1.6.28
  jiffy: ^4.1.0
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.15
  provider: ^5.0.0
  shared_preferences: ^0.5.12+4
  mask_text_input_formatter: ^2.0.0
  hexcolor: ^2.0.6
  flutter_speed_dial: ^3.0.5
  flutter_local_notifications: ^4.0.1+2
  syncfusion_flutter_pdfviewer: 18.4.49-beta
  confirm_dialog: ^1.0.0
  package_info: ^2.0.2
  sembast: ^3.1.2
  path: ^1.8.0
  flutter_dotenv: ^5.0.2


dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/images/
    - release.env
    - debug.env

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/sf_regular.ttf
